### ISSUE TITLE
'resultado' is not defined

### ISSUE THREAD

**Issue by shermilaguerra** [mrioqueiroz/captcha-lab#1]
O que posso mudar para que dê certo com minhas imagens? Elas tem o mesmo ruido das suas imagens.

**Comment by mrioqueiroz** [comment]
Olá, @shermilaguerra 

Adicionei um [script](https://github.com/mrioqueiroz/captcha-lab/blob/68eb9b232d9a68c095ec8ffda66c9e527ed96447/script.py) que talvez possa ajudar nas imagens que você está trabalhando. Nele você vai encontrar as seguintes constantes que podem ser alteradas pra adequar ao tipo de captcha:

```
LIMITE_RUIDOS
LIMITE_REFORCO
ITERACOES_LIMPEZA
ITERACOES_REFORCO
```

A chamada do script ficaria da seguinte forma:

`python script.py nome-da-imagem.png limite_ruidos limite_reforco interacoes_limpeza interacoes_reforco`

Nos testes que eu fiz aqui, consegui obter melhores resultados com a seguinte configuração:

```python
LIMITE_RUIDOS = 1.8
LIMITE_REFORCO = 1.8
ITERACOES_LIMPEZA = 4
ITERACOES_REFORCO = 8
```

Alterei também o notebook pra resolver o erro que você citou (`'resultado' is not defined`): 68eb9b232d9a68c095ec8ffda66c9e527ed96447

Espero ter ajudado. Qualquer coisa, só avisar.
